### ISSUE TITLE
This app is blocked

### ISSUE THREAD

**Issue by dylan-sam** [theevann/piano-booking#2]
When I try to sign in to the website using Google, I get the following error message :

"Cette application est bloquée
Cette application a tenté d'accéder à des informations sensibles de votre compte Google. Google a bloqué cet accès afin de protéger votre compte."

Since I have two-factor auth. enabled on my Google account, it is not possible to turn off this automatic behaviour when accessing less secured apps ( https://myaccount.google.com/lesssecureapps ).

**Comment by theevann** [comment]
Hello !
Google is being painful about this, it seems non trivial to tell google to let people use the app in peace...
I'll try to change the authorization that the app requires to try fix this.
Thank you for your feedback !
